### ISSUE TITLE
Error in `play_wordler()`

### ISSUE THREAD

**Issue by grddavies** [DavidASmith/wordler#3]
System: Windows
R version: 4.1.2

``` r
wordler::play_wordler()
#> Guess the WORDLE in 6 tries.
#> 
#> After each guess, the color of the letters will change to show how close your guess was to the word. e.g.
#> 
#> W E A R Y
#> The letter W is in the word and in the correct spot
#> 
#> P I L O T
#> The letter L is in the word but in the wrong spot
#> 
#> V A G U E
#> None of the letters are in the word
#> Error in sample(ubuntu_dict, 1): object 'ubuntu_dict' not found
```

<sup>Created on 2022-01-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavidASmith** [comment]
Thanks. Can you confirm how you installed the package? I think it's looking for the dictionary data included with the package. I can see ubuntu_dict.rda is in the repo. Not sure why it wouldn't be able to see it.

**Comment by grddavies** [comment]
I ran `devtools::install_github("DavidASmith/wordler")`

**Comment by grddavies** [comment]
Hang on -  works with
```r
library(wordler)
play_wordler()
```

My temptation to keep the global namespace clean got the better of me here

**Comment by DavidASmith** [comment]
OK - I suspect it needs the library() call to ensure that ubuntu_dict is available. Wonder if it's possible to be explicit when asking for it so it can get even if package not loaded via library()

**Comment by grddavies** [comment]
From `?data`:
> Use of data within a function without an envir argument has the almost always undesirable side-effect of putting an object in the user's workspace (and indeed, of replacing any object of that name already there). It would almost always be better to put the object in the current evaluation environment by data(..., envir = environment()). However, two alternatives are usually preferable, both described in the ‘Writing R Extensions’ manual.

> For sets of data, set up a package to use lazy-loading of data.

> For objects which are system data, for example lookup tables used in calculations within the function, use a file ‘R/sysdata.rda’ in the package sources or create the objects by R code at package installation time.

> A sometimes important distinction is that the second approach places objects in the namespace but the first does not. **So if it is important that the function sees mytable as an object from the package, it is system data and the second approach should be used.** In the unusual case that a package uses a lazy-loaded dataset as a default argument to a function, that needs to be specified by ::, e.g., survival::survexp.us.

**Comment by DavidASmith** [comment]
Package data now referenced as wordler::ubuntu_dict.
